name: Build and Tag on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install Dependencies
        run: make mod-download

      - name: Check Go Modules
        run: make mod-verify

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          run_args: -v

      # - name: Test
      #   run: make test

      - name: Cleanup
        run: go clean

      - name: Increment Version Tag
        id: increment_tag
        uses: softprops/action-gh-release@v0.1.15
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Push Tag
        run: git push origin ${{ steps.increment_tag.outputs.tag }}
        if: github.ref == 'refs/heads/main'
