name: Build, SemVer - FEATURE BRANCH

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
      GHB_TOKEN: ${{ secrets.PAT_TOKEN }}