name: Enforce Commit Message Format

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-commit-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check Commit Messages
        run: |
          # Define the regex pattern for the commit message format you want to enforce
          COMMIT_REGEX="^(feat|fix): .+"

          # Iterate through the commits in the push
          git rev-list --count HEAD | xargs -I {} git log --format="%s" -n 1 {} | while read -r line
          do
            if [[ ! $line =~ $COMMIT_REGEX ]]; then
              echo "Error: Commit message does not match the required format: 'feat: ...' or 'fix: ...'"
              exit 1
            fi
          done
