
name: Reusable GIT Action

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      GHB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GHB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install Dependencies
        run: make mod-download

      - name: Check Go Modules
        run: make mod-verify

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54
          args: -v

      # - name: Test
      #   run: make test
      - name: Build Package
        run: go build -v ./...

      - name: Conventional Changelog Action (Master)
        if: ${{ github.ref == 'refs/heads/main' }}
        id: changelog_master
        uses: TriPSs/conventional-changelog-action@v4.0.0
        with:
          github-token: ${{ secrets.GHB_TOKEN }}
          skip-on-empty: 'false'


      - name: Create a GitHub Semantic release (Master)
        if: ${{ github.ref == 'refs/heads/main' && steps.changelog_master.outputs.skipped == 'false' }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GHB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog_master.outputs.tag }}
          release_name: ${{ steps.changelog_master.outputs.tag }}
          body: ${{ steps.changelog_master.outputs.clean_changelog }}

      - name: Cleanup
        run: go clean
